### ISSUE TITLE
isClass Item, Weapon, or Magazine

### ISSUE THREAD

**Issue by Vampurica** [SMVampire/VEMF#10]
Not sure how to check if a classname is an item and not a weapon, as they are both in CfgWeapons.

Until this is sorted crates will only have items, not weapons.

```
hint str(isClass (configFile >> "cfgWeapons" >> "FirstAidKit"));
```

Returns True.

**Comment by Vampurica** [comment]
Should be able to use inheritsFrom.

**Comment by SnarkIndustries** [comment]
Add a check to see if the "weapon" has magazines defined. 
1. Has magazines = is a weapon
2. No magazines = is an item

_magazineTypes = [configFile >> "CfgWeapons" >> _this,"magazines",[]] call BIS_fnc_returnConfigEntry;

Replace _this with the item classname.

**Comment by Vampurica** [comment]
The current version is using BIS_fnc_returnParents and seems to be working, but that is a good solution.
I'll leave this open in case the current way causes issues.

**Comment by Vampurica** [comment]
Working fine so far. Closing unless issue arises.
