### ISSUE TITLE
never use execVM

### ISSUE THREAD

**Issue by Skaronator** [SMVampire/VEMF#13]
Its recommend to storage the function on a variable with
`MyFunction = compileFinal "pathtofunction.sqf";`

Then can you execute the function with:
`[] spawn MyFunction` or `[] call MyFunction` (deeps in which environment you want it)

With call is it also possible to have a return value from the function.

**Comment by Vampurica** [comment]
I understand the reasoning behind this, but for the "Addons" idea of mine to work, I need to allow for addons to be able to overwrite pre-defined functions and script locations.

If there was some way to lock them from ever being changed from a client, I would be more interested in that. (I understand publicVariable and publicVariableServer is filtered, but I'm sure there are servers running filters lacking the best protection)
