### ISSUE TITLE
BIS_fnc_MP does not work in epoch

### ISSUE THREAD

**Issue by Skaronator** [SMVampire/VEMF#3]
https://github.com/SMVampire/VEMF/blob/master/%40VEMF/Addons/VEMF/Missions/DynamicTownInvasion.sqf#L71-L72

just use publicVariableEventHandler

**Comment by Vampurica** [comment]
I'll get to it

**Comment by Skaronator** [comment]
you could you `publicVariableClient` if you just want it trigger on a single client

**Comment by Vampurica** [comment]
I probably should.

**Comment by Vampurica** [comment]
Could you look at what I currently have?
I'm not getting a systemChat message.

eventHandler:
https://github.com/SMVampire/VEMF/blob/master/Mission%20Files/init.sqf

publicVariableClient:
https://github.com/SMVampire/VEMF/blob/master/VEMF/VFunctions.sqf#L428
