### ISSUE TITLE
Weighted Weapons Table

### ISSUE THREAD

**Issue by Vampurica** [SMVampire/VEMF#7]
The weapons need weighted in the future. AI with large calibers are too strong.

**Comment by forumtech** [comment]
How is the mix done now? Are they randomized or pre-configured? 

Personally I would prefer missions to be harder, rather than easy.

**Comment by Vampurica** [comment]
Currently they are random, but compared to a blacklist.
All of it is user definable.

**Comment by Vampurica** [comment]
Probably going to split up the weapons into classes like Sniper, MG, Assault, SMG, etc.
Can then just do a percentage chance per class.

**Comment by Vampurica** [comment]
Decided to just load the entire epoch table instead of removing duplicates. It should keep the same "Weighted Tables" as the Epoch team wanted in the game.
